### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by idleberg** [henrikor2/bridlensis#1]
The tag for the 0.3.0 includes the installers for 0.1.0 and 0.2.0, but not 0.3.0 :)

Also, why include the previous installers with each tag?

**Comment by henrikor2** [comment]
Tag moved to ref d7aaf5... that includes the 0.3.0 installer exe.

**Comment by idleberg** [comment]
I'm still not sure why you include _every_ previously released version in your `dist`-folder. Aside, GitHub [recommends](https://github.com/blog/1547-release-your-software) adding binary files to the release page, not the actual repository.

And lastly, is it really necessary to include the file version in the name of the jar file? I'm still tinkering with my build system for Sublime Text and no version would allow me to scrap wildcard usage.

**Comment by idleberg** [comment]
I guess the version detection using the registry is good enough, i've added a [build script](https://github.com/idleberg/BridleNSIS-Sublime-Text/blob/master/build.cmd) to the latest version of my Sublime Text package.
